# Generated by Django 3.1.6 on 2021-02-24 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Arriendo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_arriendo', models.DateTimeField()),
                ('id_cliente', models.IntegerField()),
                ('fecha_devolucion', models.DateTimeField(null=True)),
                ('id_empleado', models.IntegerField()),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('temporal_inventario', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Idioma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_tienda', models.IntegerField()),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('temporal_pelicula', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('agno_publicacion', models.IntegerField()),
                ('duracion_arriendo', models.IntegerField()),
                ('precio_arriendo', models.DecimalField(decimal_places=2, default=4.99, max_digits=4)),
                ('largo', models.IntegerField()),
                ('costo_reemplazo', models.DecimalField(decimal_places=2, default=19.99, max_digits=5)),
                ('clasificacion', models.CharField(max_length=25)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('temporal_idioma', models.IntegerField()),
            ],
        ),
    ]
