# Generated by Django 3.1.6 on 2021-02-19 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arriendo',
            name='inventario',
        ),
    ]
