# Generated by Django 3.1.6 on 2021-02-24 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='arriendo',
            name='inventario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='servicio.inventario'),
        ),
        migrations.AddField(
            model_name='inventario',
            name='pelicula',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='servicio.pelicula'),
        ),
        migrations.AddField(
            model_name='pelicula',
            name='actores',
            field=models.ManyToManyField(to='servicio.Actor'),
        ),
        migrations.AddField(
            model_name='pelicula',
            name='categorias',
            field=models.ManyToManyField(to='servicio.Categoria'),
        ),
        migrations.AddField(
            model_name='pelicula',
            name='idioma',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='servicio.idioma'),
        ),
    ]
